// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdIX9C9XtlmNbBxhfOPLmJXDRlDbBsNDE',
    appId: '1:134292095717:android:b340edda7de4e546c14a0c',
    messagingSenderId: '134292095717',
    projectId: 'salah-mode-66d19',
    storageBucket: 'salah-mode-66d19.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0eqWZWl9xfgBot5FMYdZu6WGWDDG5OQE',
    appId: '1:134292095717:ios:caf07a2786afdd2bc14a0c',
    messagingSenderId: '134292095717',
    projectId: 'salah-mode-66d19',
    storageBucket: 'salah-mode-66d19.firebasestorage.app',
    androidClientId: '134292095717-a2gjqheghttufeuoepk72vb4i6npk3rg.apps.googleusercontent.com',
    iosClientId: '134292095717-gint14nv73dm90ja9ki4dcbv9ecdicjb.apps.googleusercontent.com',
    iosBundleId: 'com.example.salahMode',
  );
}
